### PR TITLE
refac: Migrate all datasets db operation to drizzle on NextJs

### PR DESCRIPTION
**Pull request by alviskalev**
closed https://github.com/lmnr-ai/lmnr/issues/82

----

> [!IMPORTANT]
> Migrated dataset database operations from SQLx to Drizzle ORM in both backend and frontend, updating routes and pages accordingly.
> 
>   - **Backend Migration**:
>     - Removed SQLx-based functions `create_dataset`, `get_datasets`, `count_datasets`, and `rename_dataset` from `datasets.rs`.
>     - Removed corresponding routes from `routes/datasets.rs`.
>     - Updated `main.rs` to remove unused dataset routes.
>   - **Frontend Migration**:
>     - Replaced `fetcher` calls with Drizzle ORM queries in `route.ts` for dataset operations.
>     - Updated `page.tsx` to use Drizzle ORM for dataset retrieval.
>   - **Misc**:
>     - Removed unused imports and functions related to SQLx in affected files.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=lmnr-ai%2Flmnr&utm_source=github&utm_medium=referral)<sup> for fadd191733d1558312ef2023896b6d80cb1d0466. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by dinmukhamedm — COMMENTED** [review]
Looks good to me. Let's test and remove the relevant app-server code before we can merge this

**Comment by alviskalev** [comment]
hey @dinmukhamedm just wanna confirm before I delete this, this response `any_in_project` isn’t used in any frontend component, right?
Screenshot 2024-11-12 at 22 18 47

**Comment by alviskalev** [comment]
btw just info that the POST method for updating a dataset in `frontend/app/api/projects/[projectId]/datasets/[datasetId]/route.ts` is not used anywhere in the codebase

**Comment by dinmukhamedm** [comment]
> this response any_in_project isn’t used in any frontend component, right?

Yes, this is for consistency with get evaluations and get traces where we used it to show a page placeholder if there are none. However, this is already done separately in the frontend. We can remove this, this is safe.

> I think we no need to move the delete method for the dataset to Next.js, as there is semantic search that handles the deletion operation.

Great catch! Let's keep it for now. Later we may want to move that request to the frontend too, but it's gRPC, so it is a little bit more work

> btw just info that the POST method for updating a dataset in `frontend/app/api/projects/[projectId]/datasets/[datasetId]/route.ts` is not used anywhere in the codebase

yep, saw that, we can delete that.

**Review by dinmukhamedm — APPROVED** [review]
Thanks a ton!

**Pull request merged**
